### PR TITLE
Set C++ version for boost thread

### PR DESCRIPTION
**Pull request by aWZHY0yQH81uOYvH**
Fixes https://github.com/thliebig/openEMS-Project/issues/190

As of recent, `nf2ff` has been failing to compile with the latest version of boost (1.84.0):

```
In file included from /tmp/openEMS-Project/openEMS/nf2ff/nf2ff.cpp:19:
In file included from /tmp/openEMS-Project/openEMS/nf2ff/nf2ff_calc.h:26:
In file included from /usr/local/include/boost/thread.hpp:24:
In file included from /usr/local/include/boost/thread/future.hpp:31:
In file included from /usr/local/include/boost/thread/detail/invoker.hpp:32:
/usr/local/include/boost/thread/csbl/tuple.hpp:19:18: error: no member named 'tuple' in namespace 'std'
    using ::std::tuple;
          ~~~~~~~^
/usr/local/include/boost/thread/csbl/tuple.hpp:21:18: error: no member named 'make_tuple' in namespace 'std'
    using ::std::make_tuple;
          ~~~~~~~^
```

[They changed around some stuff in this header file.](https://github.com/boostorg/thread/commit/515d95c4413a28aaa822e48a7a2bbc5b71921528#diff-b84166086f26c96a822fcc2cff5174fc8888f84146ab68c76b80df7b7415aa8d)

Setting the C++ version to 11 fixes this for me on
```
% clang --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: x86_64-apple-darwin23.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

### CODE REVIEW

**Comment by aWZHY0yQH81uOYvH** [comment]
Fixes #190 (apart from Python build missing, and Qt6 missing from dependencies list in docs)

**Comment by thliebig** [comment]
Hmm, I'm always a but hesitant with such changes as people may want to compile openEMS on e.g. very old machines with potentially an even older compiler?  
And on my quite up to date gcc I do not see this issue either.
Maybe we should put this behind a compiler switch (only for clang) or only for mac?? At least for the time being?
Opinions?

**Comment by aWZHY0yQH81uOYvH** [comment]
On my install of GCC 13, it looks like the default `__cplusplus` version without any `--std` argument supplied is C++ 17, whereas on clang it's C++ 98. Specifying `--std=c++98` for GCC makes it spit out even more errors than clang when dealing with the same `boost/thread.hpp` header.

It's mainly a problem with the combination of the old C++ standard and the new version of Boost, which uses C++ 11 features. Presumably an old machine that doesn't have a C++ 11 compiler wouldn't also be using a new version of Boost that requires a C++ 11 compiler.

I suppose the inclusion of this CMake line could be made dependent on the detected Boost version rather than the host platform or compiler? But honestly, I doubt there are many machines out there worth running openEMS on that don't have a C++ 11 compiler.

**Comment by aWZHY0yQH81uOYvH** [comment]
Another consideration would be if this change (whatever its final form may be) should be moved elsewhere in the project, since `nf2ff` isn't the only thing using Boost. This specific header file is also used in the openEMS multithread engine as well.

**Comment by aWZHY0yQH81uOYvH** [comment]
It looks like setting the C++ version to something the current compiler doesn't support is OK. According to [the CMake docs](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD_REQUIRED.html),
> If [CXX_STANDARD_REQUIRED] is OFF or unset, the [CXX_STANDARD](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD) target property is treated as optional and may "decay" to a previous standard if the requested is not available.

So this shouldn't break the compilation with an older compiler as long as whatever dependency libraries are OK with the older C++ standard.

**Comment by thliebig** [comment]
Thanks for the analysis. Let's just apply this and cross our fingers that nothing breaks :wink:

**Comment by aWZHY0yQH81uOYvH** [comment]
Sounds good 🙂

Looks like something somewhere is setting C++ 11 for the main openEMS build, which is why this change is only needed for `nf2ff`, so It's Probably Fine™
